kurakke/nitkit-shot

- package-lock.json
- package.json
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/styles/index.css
- src/views/pages/Root/index.tsx
- tailwind.config.js
以下のissueに関するプルリクエストです。
https://github.com/kurakke/nitkit-shot/issues/9
1. nextUIのインストール
2. 1に伴うpages下の_appと_documentへの追記
3. tailwind.configのpluginとcontentの編集
を行いました。
導入できたことを分かりやすくするために、views/pages/Root/index.tsxにモックの要素を追加してあるので、チェックをお願いします。
> NextUIを導入しました。

- src/components/layouts/DefaultLayout.tsx
- src/views/pages/Root/index.tsx
- types/LayoutProps.ts
以下のissueに関するプルリクエストです。
#31 
1. types/LayoutPropsを削除し、DefaultLayoutで同様のものを定義
2. オブジェクトに最低限の幅を確保できるようにする
を行いました。
> デフォルトレイアウトの修正

- src/components/layouts/Footer.tsx
以下のissueに関するプルリクエストです。
#33 
フッターのマージンの調整を行いました。
> フッターのサイズを修正

- src/components/general/RedirectButton.tsx
- src/components/general/SentenceGeneration.tsx
- src/components/general/TitleText.tsx
- src/components/topPage/About/index.tsx
- src/views/pages/Root/index.tsx
- types/Sentence.ts
以下のIssueに関するプルリクエストです。
#26 
トップページのAbout部分の実装を行いました。
> トップページのAbout部分の実装

- constants/menuItems.ts
以下のissueに関するプルリクエストです。
#63 
まだ出来上がってない3つのページの遷移先をComing Soonページに変更しました。
> Ranking,Movie,Q&Aページの遷移先をComing Soonに変更

- constants/menuItems.ts
Reverts kurakke/nitkit-shot#64
> Revert "Ranking,Movie,Q&Aページの遷移先をComing Soonに変更"

- src/components/layouts/Footer.tsx
> Footerの余白を調整

- src/components/general/RedirectButton.tsx
> RedirectButtonの構造を修正

- src/views/pages/Root/index.tsx
> トップページへの余白の追加

- src/components/layouts/HeadBar.tsx
> ヘッダーのロゴをタップするとトップページに移動する機能を追加

- constants/informationData.ts
- src/components/topPage/Information/index.tsx
- types/information.ts
> インフォメーションの本番データを入力

- src/components/layouts/Footer.tsx
- src/components/layouts/HeadBar.tsx
- tailwind.config.js
以下のIssueのPRの一部です。
#39 
ヘッダーとフッターにシャドウを追加しました。
> HeadBarとFooterのcssにshadow-xlを追加

- src/components/layouts/HeadBar.tsx
以下のIssueに対するPRです。
#98 
項目の大きさや間隔のほか、上下の余白を実装しました。
> ハンバーガーメニューの項目を調整

- package-lock.json
- package.json
> analytics用のパッケージ導入

- src/components/general/ComingSoon/ComingSoonTape.tsx
- src/components/general/ComingSoon/KeepOutTape.tsx
- src/components/general/ComingSoon/index.tsx
- src/components/rankingPage/RankingTab.tsx
- src/components/rankingPage/index.tsx
- tailwind.config.js
以下のissueのPRです。
#109 
coming soonコンポーネントのkeep outをcoming soonに書き換えました。
また、併せてRankingTabのCSS部分のミスを訂正しました。
> keep outをcoming soonに変更とRankingTabのCSSを訂正

- src/views/pages/Ranking/index.tsx
以下のissueに関するPRです。
#119 
ランキングページの内容をカミングスーンに差し替えました。
> RankingをComingSoonに変更

- src/util/log.ts
- src/views/pages/Root/index.tsx
> console.logにメッセージ乗っけました

- constants/gamingVisual.ts
> OP動画のURL差し替え

- src/components/forPlayerPage/index.tsx
> ForPlayerの黄色い見出しを削除

- src/components/layouts/Footer.tsx
以下のissueのPRです。
#123 
フッターのロゴを押すとトップページに移動するように変更しました。
> フッターのロゴを押すとトップページに移動するように変更

- src/pages/_document.tsx
以下のissueのPRです。
#159 
ページの言語を日本語に設定しました。
> 自動翻訳を無効にしよう

- constants/informationData.ts
- src/components/topPage/Information/index.tsx
- types/information.ts
> informationの要素からidを削除

- src/views/pages/QAndA/index.tsx
- src/views/pages/Root/index.tsx
> ファイルのフォーマット

- constants/comments.ts
- constants/menuItems.ts
- src/components/commentPage/CommentContents.tsx
- src/components/commentPage/index.tsx
- types/PageId.ts
> クレジットにデータを追加

- constants/comments.ts
> rename: メッセージの修正

- src/components/commentPage/CommentContents.tsx
> update: 左右の余白の調整

- constants/informationData.ts
> 二日目開始を伝えるインフォメーションデータを追加
